### ISSUE TITLE
FooterView not working

### ISSUE THREAD

**Issue by anuraagdjain** [MichiganLabs/AnimatingTableViewHeader#3]
I tried adding the footerView. When the header is expanded and just scroll the tableview and can view the footerView , but when I try collapsing the header i.e, the tableView is expanded completely , the footerView is not viewed. 

Edit: 
1. TableView Style - Plain
2. Tried adding the footer view to your project, result it the same. 

This one returns a sticky footer view, which I don't want. 
`func tableView(_ tableView: UITableView, viewForFooterInSection section: Int) -> UIView? {
        return myView
    }`

and this one return at the last, but not viewing properly. 
`self.tableView.tableFooterView =  myView `

Check the image here http://imgur.com/a/sNKkY

**Comment by johndelong** [comment]
Hi @anuraagdjain!

If you want a **single** footer view at the end of your table and not a **section** footer view, then setting `self.tableView.tableFooterView` is the correct approach. Check out [this answer](http://stackoverflow.com/a/38178757) on stackoverflow for ideas on how to add your own custom footer view to a `UITableView`.

I am going to close this issue as I do not believe it is a problem with the project itself but rather a question on how to customize it. When it comes to customizing this project to fit your needs, please check out [stack overflow](https://stackoverflow.com/) for implementation questions as it will likely help you to more quickly solve your problem.

If I have misunderstood your situation, and there is a problem with this project, feel free to leave a comment with a code snippet so that I can better troubleshoot the issue. Thanks!

**Comment by anuraagdjain** [comment]
Hi, I followed the same way. And it didn't work , so I've added another
cell to show my footer content and it works fine.

**Comment by anuraagdjain** [comment]
I think you can try adding self.tableView.tableFooterView and verify
yourself that footer view animates and expands based on the height of other
cells.
