### ISSUE TITLE
isScrollingDown and isScrollingUp - appear in revserse

### ISSUE THREAD

**Issue by ashish-naik** [MichiganLabs/AnimatingTableViewHeader#6]
When i scroll down, isScrollingDown derives as false and if i scroll up then isScrollingUp is false.

why this opposite calculation?

I have UISearchBar in place UIView.

when i scroll up, `scrollView.contentOffset.y` gives positive value. Should it not give negative?

Thanks
Ashish

```
func scrollViewDidScroll(_ scrollView: UIScrollView) {
        
        let scrollDiff = scrollView.contentOffset.y - self.previousScrollOffset
       
        let absoluteTop: CGFloat = 0;
        let absoluteBottom: CGFloat = scrollView.contentSize.height - scrollView.frame.size.height;
        
        let isScrollingDown = scrollDiff > 0 && scrollView.contentOffset.y > absoluteTop
        let isScrollingUp = scrollDiff < 0 && scrollView.contentOffset.y < absoluteBottom
       
        var newHeight = self.searchBarHeightConstraint.constant


        if isScrollingDown {
            newHeight = max(self.minHeaderHeight, self.searchBarHeightConstraint.constant - abs(scrollDiff))
            
        } else if isScrollingUp {
            newHeight = min(self.maxHeaderHeight, self.searchBarHeightConstraint.constant + abs(scrollDiff))
            

            newSearchBar.showsScopeBar = false
            
        }

      if newHeight != self.searchBarHeightConstraint.constant {
            self.searchBarHeightConstraint.constant = newHeight
            self.setScrollPosition(position: self.previousScrollOffset)

        }

        self.previousScrollOffset = scrollView.contentOffset.y

{
```

**Comment by johndelong** [comment]
@ashish-naik  Hmm, that is peculiar. Your code looks correct. In-fact, I've copied it over into my project and it seems to operate as I would expect. 

Is it perhaps that we have opposite interpretations of what scroll directions are? For me when I am "scrolling down", I drag up with my finger (or mouse when on a simulator) so that I can view more content **downward** on the page. Vice versa when I am "scrolling up". The biggest tell tale is the scroll bar on the right hand side. If the scroll bar is going down, you are scrolling down. If it is going up, you are scrolling up. This scroll direction interpretation is pretty typical.

Let me know if you are seeing something different than what I've described above and in this screen recording below.

![scroll_direction](https://user-images.githubusercontent.com/4023203/38470303-af00bf1a-3b2e-11e8-968f-4fc2439276e7.gif)

**Comment by ashish-naik** [comment]
I get it now and feel so ashamed I didn't thought the natural way !!!

Will check again. Thanks.

**Comment by johndelong** [comment]
No problem! Glad we were able to get to the bottom of it! 👍

**Comment by ashish-naik** [comment]
yes it working fine. Thanks.
